### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by joystein** [tilgovi/pyramid-oauthlib#11]
Thanks for this project @tilgovi. Could you please consider publishing a new release to pip? In particular py3 support, which seems to be in place in master, would be nice.

**Comment by tilgovi** [comment]
@joystein since you just made the PR for client params, anything else you think we need to do before I make a release?

**Comment by joystein** [comment]
@tilgovi : not at the moment. I might have a few more things to contribute later, but don't know when I will have time.

**Comment by aodag** [comment]
@tilgovi i wanna use this products on python3!

**Comment by tilgovi** [comment]
Thanks for the bump! I'll make it happen in the next day or so.

**Comment by tilgovi** [comment]
Thanks for the bump! I'll make it happen in the next day or so.
