### ISSUE TITLE
Pyramid 1.10 Support

### ISSUE THREAD

**Issue by CasperCL** [tilgovi/pyramid-oauthlib#14]
In Pyramid 1.10 the method set_request_property of the Pyramid Configuration class has been removed:

> Removed pyramid.config.Configurator.set_request_property which had been deprecated since Pyramid 1.5. Instead use pyramid.config.Configurator.add_request_method with reify=True or property=True. See https://github.com/Pylons/pyramid/pull/3368

Seems like a simple fix. I'll submit a PR.

**Comment by tilgovi** [comment]
Version 0.4.0 is released. Thanks again 🙌.
