### ISSUE TITLE
OAuthLib 3 support

### ISSUE THREAD

**Issue by tilgovi** [tilgovi/pyramid-oauthlib#17]

**Comment by cehbrecht** [comment]
+1

**Comment by tilgovi** [comment]
@cehbrecht if you're interested in helping, please go ahead. I'll review and merge PRs, and if you want to carry it all the way through and help maintain, I would add you as a collaborator. I don't do a lot of Pyramid work these days, but I do try to keep the library going. Thank you for your other PR.

**Comment by cehbrecht** [comment]
@tilgovi I can try to update ... but I don't promise.

**Comment by mmanderson** [comment]
I put up a PR for that today. It at least allows pyramid-oauthlib to work with Pyramid 2 and OAuthLib 3 implementations.

**Comment by tilgovi** [comment]
Closed by #20. Thanks, again!
